// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIcxy_okjQHAoac7HPIU1xmqhhLrUENFU',
    appId: '1:650252634209:web:b329456bc4387bd64cc220',
    messagingSenderId: '650252634209',
    projectId: 'photodukan-com',
    authDomain: 'photodukan-com.firebaseapp.com',
    storageBucket: 'photodukan-com.firebasestorage.app',
    measurementId: 'G-19RF4GSZZB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDm9RgVoCMtq2mA24DDHkX1qb23ObB0GwU',
    appId: '1:650252634209:android:28c40ec4d23b63e94cc220',
    messagingSenderId: '650252634209',
    projectId: 'photodukan-com',
    storageBucket: 'photodukan-com.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrjTa4_MF4KSuSZ_Jwsska14Hmv52yQso',
    appId: '1:650252634209:ios:1416e68ef928d4734cc220',
    messagingSenderId: '650252634209',
    projectId: 'photodukan-com',
    storageBucket: 'photodukan-com.firebasestorage.app',
    iosBundleId: 'com.photodukan.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrjTa4_MF4KSuSZ_Jwsska14Hmv52yQso',
    appId: '1:650252634209:ios:1416e68ef928d4734cc220',
    messagingSenderId: '650252634209',
    projectId: 'photodukan-com',
    storageBucket: 'photodukan-com.firebasestorage.app',
    iosBundleId: 'com.photodukan.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIcxy_okjQHAoac7HPIU1xmqhhLrUENFU',
    appId: '1:650252634209:web:699ba76303af83f14cc220',
    messagingSenderId: '650252634209',
    projectId: 'photodukan-com',
    authDomain: 'photodukan-com.firebaseapp.com',
    storageBucket: 'photodukan-com.firebasestorage.app',
    measurementId: 'G-9MTEXQN6XB',
  );
}
